### ISSUE TITLE
Missing source code

### ISSUE THREAD

**Issue by Pathoschild** [ylsama/RightClickMoveMode#1]
It looks like this repository doesn't contain any of the code, it only has the compiled files. Is that deliberate?

**Comment by nghiango1** [comment]
Sorry about that, I updated it.
Because I'm not familiar with Github, most of my update is by hand over web interfaces. Besides, it was pre-release and not optimal in code yet, so I decide not to upload it just yet.

**Comment by Pathoschild** [comment]
If you want, come ask in [#modding on the Stardew Valley Discord](https://stardewvalleywiki.com/Modding:Community#Discord) and we'll help you set up Git. It'll be much easier to commit changes that way than uploading files through the web UI. :)

**Comment by nghiango1** [comment]
Thanks, I have already join SDV Discord. And the newest source code is here, finally done clean up my mess.

**Comment by Pathoschild** [comment]
Thanks!
