### ISSUE TITLE
[Feature Request] Pathfinding for clicking

### ISSUE THREAD

**Issue by PinkSerenity** [ylsama/RightClickMoveMode#10]
I know that this will probably break the scope of this mod, but pathfinding would be a really neat feature. It would certainly help thinking less about controls and more about what to do.

To make it even more like the mobile version, clicking on an object could make the farmer run to it, then interacting with it automatically using the correct tool (if it's in the inventory).

While it's probably a hassle and not worth your time, I just wanted to wish for it because, well, nothing bad can happen.

**Comment by nghiango1** [comment]
Could be possible.
I have already try once implement a* but the performance is worst than expected, so it never being release.

**Comment by PinkSerenity** [comment]
I thought so. I wish it could work as it does on mobile, it seems a lot easier there. Nevertheless, thank you for this amazing mod.

**Comment by nghiango1** [comment]
I retry it again, check the a_star branch for the latest dev verson
