### ISSUE TITLE
Repository not up-to-date?

### ISSUE THREAD

**Issue by Pathoschild** [ylsama/RightClickMoveMode#8]
The repository seems to be outdated: Right-Click Move Mode is version 1.2 on Nexus, but the repository has version 1.1.8. Can you make sure the latest code is committed? (I'm going to submit a pull request for SMAPI 3.0 compatibility.)

**Comment by nghiango1** [comment]
Sorry for being this late, 1.2 is up now

**Comment by Pathoschild** [comment]
@ylsama Thanks!

What do you think of having one solution that contains both mods (instead of one branch per mod)? That's the usual approach, and it's easier to view the code and submit pull requests. If that sounds okay, I'll submit a pull request to do it (along with some updates for SMAPI 3.0).

**Comment by nghiango1** [comment]
Thanks, It is great to get your help. 

While I only work on 1 mod in this Repository, Move Through Object is another mod that in my Branch. It is actually a failure way to fix my main mod, so I believe that it was not worth keeping up. I will delete/archived it later when SMAPI 3.0 come

**Comment by nghiango1** [comment]
I mess thing up. I fix things and made changes in preparation for SMAPI 3.0 too.

**Comment by Pathoschild** [comment]
Thanks! Your recent changes work fine with SMAPI 3.0.
