### ISSUE TITLE
Local co-op

### ISSUE THREAD

**Issue by Davidbtnl** [ylsama/RightClickMoveMode#9]
How to use the mod with Local co-op mode? Both players are moving by using the mouse. Is this supported yet for local co-op?

**Comment by nghiango1** [comment]
I don't think so, i haven't had time to get back to the mod for a long time so let me see this again

**Comment by nghiango1** [comment]
Hmm, I check it with LAN co-op mode and it work fine.

If it still a problem I will reopen this issus.
